---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-pod
  namespace: horizontal-pod-autoscaler
spec:
  selector:
    matchLabels:
      app: hpa-pod
  template:
    metadata:
      labels:
        app: hpa-pod
    spec:
      containers:
        - name: hpa-pod
          image: aputra/myapp-195:v2
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m